import { Injectable } from '@angular/core';
import { Food } from '../../shared/models/Food';

@Injectable({
  providedIn: 'root'
})

export class FoodService {

  constructor() { }

  //Creating function for getAll food image
  getAll():Food[]{

    return[
      {
        id:1,
        Food_Name: 'Salami Sandwiches',
        price: 5.95,
        cookTime: '10-15',
        favorite: false,
        origins: ['US','Germany', 'Finland', 'Globe'],
        stars: 3.8,
        imageURL: '/assets/images/foods/Food_1.jpg',
        tags: ['Fastfood', 'Popular', 'Salami','Non-veg'],
      },
      {
        id:2,
        Food_Name: 'Burger Luxury',
        price: 10.5,
        cookTime: '15-25',
        favorite: true,
        origins: ['US','Germany', 'Finland', 'globe'],
        stars: 4.5,
        imageURL: '/assets/images/foods/Food_2.jpg',
        tags: ['Burgers','popular','Non-veg'],
      },
      {
        id:3,
        Food_Name: 'Hung Far Low Pork Burger',
        price: 15.5,
        cookTime: '25-30',
        favorite: true,
        origins: ['US', 'Globe'],
        stars: 3.5,
        imageURL: '/assets/images/foods/Food_3.jpg',
        tags: ['Burger','Popular'],
      },
      {
        id:4,
        Food_Name: 'Creamy garlic seafood pasta',
        price: 25.5,
        cookTime: '35',
        favorite: false,
        origins: ['Europe','US'],
        stars: 3.7,
        imageURL: '/assets/images/foods/Food_4.jpg',
        tags: ['Seafood','Non-veg','Pasta'],
      },
      {
        id:5,
        Food_Name: 'Easy Cheesy Pizza Dip',
        price: 29.95,
        cookTime: '45',
        favorite: true,
        origins: ['Europe','Globe'],
        stars: 4.5,
        imageURL: '/assets/images/foods/Food_5.jpg',
        tags: ['Pizza','Vegetarian','Popular'],
      },
      {
        id:6,
        Food_Name: 'Spaghetti Alla Nerano',
        price: 25.5,
        cookTime: '24',
        favorite: true,
        origins: ['Europe', 'Globe'],
        stars: 5.0,
        imageURL: '/assets/images/foods/Food_6.jpg',
        tags: ['Pasta','Vegetarian','Delicous'],
      },
      {
        id:7,
        Food_Name: 'Flavor bomb sandwiches',
        price: 25.5,
        cookTime: '21',
        favorite: true,
        origins: ['Globe', 'European', 'us'],
        stars: 3.6,
        imageURL: '/assets/images/foods/Food_7.jpg',
        tags: ['Sandwich','Vegetarian','Popular'],
      },
      {
        id:8,
        Food_Name: 'Combination of sushies',
        price: 25.5,
        cookTime: '65',
        favorite: false,
        origins: ['Japan','Globe'],
        stars: 1.5,
        imageURL: '/assets/images/foods/Food_8.jpg',
        tags: ['Sushi','Asian flavor','Popular','Non-veg'],
      },
      {
        id:9,
        Food_Name: 'New Suhies of Japan',
        price: 55.15,
        cookTime: '25',
        favorite: false,
        origins: ['Japan', 'Globe'],
        stars: 2.5,
        imageURL: '/assets/images/foods/Food_9.jpg',
        tags: ['Sushi','Asian flavor','Popular','Non-veg'],
      },
      {
        id:10,
        Food_Name: 'Kebab vegpizza',
        price: 35.5,
        cookTime: '25-65',
        favorite: true,
        origins: ['Europe','Us','Asia','Americans'],
        stars: 4.5,
        imageURL: '/assets/images/foods/Food_10.jpg',
        tags: ['Pizza','Popular','European flavor','Non-veg'],
      },
      {
        id:11,
        Food_Name: 'Full vegtarian Pasta',
        price: 39.95,
        cookTime: '24',
        favorite: true,
        origins: ['Europe','Us','Asia','Americans'],
        stars: 4.5,
        imageURL: '/assets/images/foods/Food_11.jpg',
        tags: ['Vegetarian','Popular','European flavor','Pasta','Healty'],
      },
      {
        id:12,
        Food_Name: 'Salad mix colorfull',
        price: 13.99,
        cookTime: '15',
        favorite: false,
        origins: ['Globe','Europe'],
        stars: 4.5,
        imageURL: '/assets/images/foods/Food_12.jpg',
        tags: ['Vegetarian','Salad','Healthy'],
      },
      {
        id:13,
        Food_Name: 'Bread mix salad',
        price: 12.75,
        cookTime: '15-17',
        favorite: true,
        origins: ['Globe','Europe'],
        stars: 4.5,
        imageURL: '/assets/images/foods/Food_13.jpg',
        tags: ['Vegetarian','Salad','Healthy'],
      },
      {
        id:14,
        Food_Name: 'Fish lemon flavor',
        price: 9.55,
        cookTime: '15-25',
        favorite: true,
        origins: ['Globe','Us','Europe',],
        stars: 4.5,
        imageURL: '/assets/images/foods/Food_14.jpg',
        tags: ['Non-veg','Fish','Curry'],
      },
      {
        id:15,
        Food_Name: 'Seafish soup flavor bomb',
        price: 45.15,
        cookTime: '25',
        favorite: false,
        origins: ['Us','Europe'],
        stars: 1.5,
        imageURL: '/assets/images/foods/Food_15.jpg',
        tags: ['Non-veg','Soup','SeaFish'],
      },
      {
        id:16,
        Food_Name: 'Garlic coriander soup',
        price: 18.95,
        cookTime: '15-25',
        favorite: false,
        origins: ['Us','Europe'],
        stars: 1.5,
        imageURL: '/assets/images/foods/Food_16.jpg',
        tags: ['Soup','Vegetarian','Healty'],
      },
      {
        id:17,
        Food_Name: 'Chicken panbake salad',
        price: 12.50,
        cookTime: '19',
        favorite: true,
        origins: ['Europe'],
        stars: 3.1,
        imageURL: '/assets/images/foods/Food_17.jpg',
        tags: ['Chicken','Salad','Healty','Non-veg'],
      },
      {
        id:18,
        Food_Name: 'Veg flavors bomb salad',
        price: 16.65,
        cookTime: '15-25',
        favorite: true,
        origins: ['Europe','Globe','US'],
        stars: 4.5,
        imageURL: '/assets/images/foods/Food_18.jpg',
        tags: ['Vegetraian','Healthy'],
      },
      {
        id:19,
        Food_Name: 'Indian Curry food',
        price: 35.95,
        cookTime: '65',
        favorite: true,
        origins: ['Asia'],
        stars: 4.5,
        imageURL: '/assets/images/foods/Food_19.jpg',
        tags: ['Non-veg','Delcious','Asian flavor'],
      },
      {
        id:20,
        Food_Name: 'Middle-East biryani multi-color rise',
        price: 26.5,
        cookTime: '45',
        favorite: true,
        origins: ['Asia'],
        stars: 4.5,
        imageURL: '/assets/images/foods/Food_20.jpg',
        tags: ['Chicken','Non-veg','Delicious','Asian flavor'],
      }
    ]
  }
}


