import { Injectable } from '@angular/core';
import { Food } from '../../shared/models/Food';

@Injectable({
  providedIn: 'root'
})

export class FoodService {

  constructor() { }

  //Creating function for getAll food image
  getAll():Food[]{

    return
    [
      {
        id:1,
        Name: 'Salami Sandwiches',
        cookTime: '10-15',
        favorite: false,
        origins: ['us','Germaby', 'Finland', 'globe'],
        starts: 3.8,
        imageURL: '/assets/images/foods/Food_1.jpg',
        tags: ['Fastfood','Breadfood', 'popular', 'Salami'],
      },
      {
        id:2,
        Name: 'Burger Luxury',
        cookTime: '15-25',
        favorite: true,
        origins: ['us','Germaby', 'Finland', 'globe'],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_2.jpg',
        tags: ['Fastfood','Burger', 'popular', 'Beef', 'Cheese'],
      },
      {
        id:3,
        Name: '',
        cookTime: '',
        favorite: true,
        origins: [''],
        starts: ,
        imageURL: '/assets/images/foods/Food_3.jpg',
        tags: [''],
      },
      {
        id:4,
        Name: '',
        cookTime: '',
        favorite: false,
        origins: [''],
        starts: 2.5,
        imageURL: '/assets/images/foods/Food_4.jpg',
        tags: [''],
      },
      {
        id:5,
        Name: '',
        cookTime: '',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_5.jpg',
        tags: [''],
      },
      {
        id:6,
        Name: '',
        cookTime: '',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_6.jpg',
        tags: [''],
      },
      {
        id:7,
        Name: 'B',
        cookTime: '15-25',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_7.jpg',
        tags: [''],
      },
      {
        id:8,
        Name: '',
        cookTime: '15-25',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_8.jpg',
        tags: [''],
      },
      {
        id:9,
        Name: '',
        cookTime: '',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_9.jpg',
        tags: [''],
      },
      {
        id:10,
        Name: '',
        cookTime: '15-25',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_10.jpg',
        tags: [''],
      },
      {
        id:11,
        Name: '',
        cookTime: '',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_11.jpg',
        tags: [''],
      },
      {
        id:12,
        Name: '',
        cookTime: '',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_12.jpg',
        tags: [''],
      },
      {
        id:13
        Name: '',
        cookTime: '15-25',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_13.jpg',
        tags: [''],
      },
      {
        id:14,
        Name: '',
        cookTime: '15-25',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_14.jpg',
        tags: [''],
      },
      {
        id:15,
        Name: '',
        cookTime: '15-25',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_15.jpg',
        tags: [''],
      },
      {
        id:16
        Name: '',
        cookTime: '15-25',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_16.jpg',
        tags: [''],
      },
      {
        id:17,
        Name: '',
        cookTime: '15-25',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_17.jpg',
        tags: [''],
      },
      {
        id:18,
        Name: '',
        cookTime: '15-25',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_18.jpg',
        tags: [''],
      },
      {
        id:19,
        Name: '',
        cookTime: '15-25',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_19.jpg',
        tags: [''],
      },
      {
        id:20,
        Name: '',
        cookTime: '15-25',
        favorite: true,
        origins: [''],
        starts: 4.5,
        imageURL: '/assets/images/foods/Food_20.jpg',
        tags: [''],
      },
    ]
  }
}


